### ISSUE TITLE
Drop issue/request

### ISSUE THREAD

**Issue by FaanMaario** [NL-4-DEVS/PocketRPG#11]
Hi I love your plugin! **Easy to use and so fun !**

# Issue
I discover that your plugin doesn't allow to drop items; can you make an option to "_on_/_off_" it?

-
Thanks anyways :)

**Comment by Sandertv** [comment]
Sure! I'll add that to the new beta version! :)

**Comment by Sandertv** [comment]
I added it in the latest beta version on the beta branch, would you mind testing it out and see if it fits your needs? You will have to remove the old config so the plugin can regenerate a new one.

**Comment by Sandertv** [comment]
Okey this seems to work, have fun using the plugin :)
