### ISSUE TITLE
Losing RPG weapon when death, disconnected

### ISSUE THREAD

**Issue by Adam1609** [NL-4-DEVS/PocketRPG#24]
This happened when dying, losing all RPG weapon, and couldn't get it back.
I hoped:
- [ ] You will have a command-like: /rpg leave (current-class)
- [ ] Fix this bug :(

**Comment by Sandertv** [comment]
Whoops sorry! I forgot readding the keepinventory when putting the switch of itemlosing on... I'll add that real soon

**Comment by Sandertv** [comment]
Fixed in latest Beta version, might add a /rpg reset command soon.
