### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by Driesboy** [NL-4-DEVS/PocketRPG#3]

**Comment by Sandertv** [comment]
- Fix crashings/disables

**Comment by Driesboy** [comment]
not more?

**Comment by Sandertv** [comment]
Yeah way more but this is top priority

**Comment by LordJoshie** [comment]
https://photos-3.dropbox.com/t/2/AABT3xAudD5wZbxs0QIEcDEm8qpz-cQr77jpm0T_MlABcA/12/77724336/png/32x32/1/_/1/2/Screenshot_20160709-115502.png/EKXxpjwY-lggAigC/hcupXdIU3P1s3B4K3AVClW8Aaymn2AX4UW7jurZiPFE?size_mode=1&size=32x32

**Comment by LordJoshie** [comment]
![screenshot_20160709-115502](https://cloud.githubusercontent.com/assets/17371144/16708776/80d0556e-45cc-11e6-9f20-c55df4cb7bad.png)

**Comment by HyGlobalHD** [comment]
The Plugin Are Not Ready Yet.Please Be Patient.

**Comment by Sandertv** [comment]
That's right, it doesn't work just yet.

**Comment by Sandertv** [comment]
Thanks for testing it though :)

**Comment by LordJoshie** [comment]
ya'l think you  could help me make a plug we could all get great use out of ?
I have been! thinking of something where we can do /help or /howto (configurable)
and then in a config set what the commands would be, as well as what each would say. to like... override and make better what /help does, or add a /howto for intricate commands 

Possible ?

**Comment by HyGlobalHD** [comment]
@LordJoshie I think there already a plug for it.

**Comment by Sandertv** [comment]
Yeah there's something similar on forums.imagicalmine.net

**Comment by Sandertv** [comment]
RPG part has been fixed and will be improved later on, I'm going to focus on the Quest part right now.

**Comment by Sandertv** [comment]
Quests added and working, RPG being improved on later.
