### ISSUE TITLE
[ NEW API ] - Change Log

### ISSUE THREAD

**Issue by RedstoneAlmeida** [NL-4-DEVS/PocketRPG#36]
# [ NEW API ] - Change Log
## RPG
- Save Classes in configuration file
- Functions to edit classes using other plugin

#### Code:
```$this->rpg = $this->getServer()->getPluginManager()->getPlugin('PocketRPG');```

## To-Do
- Cooldown Quests
- New Classes

**Comment by Sandertv** [comment]
Cooldown quests? In the way of? :P

**Comment by RedstoneAlmeida** [comment]
idk ;-; is one suggestion to make best RPG plugin

**Comment by Sandertv** [comment]
No I mean, what do you mean exactly with cooldown quests?

**Comment by Sandertv** [comment]
Btw right now it is the best RPG plugin. (It's the only one LOL)

**Comment by RedstoneAlmeida** [comment]
missions cooldown would like to earn XP faster or items without having to recreate the cooldowns having regard to redo missions

**Comment by Sandertv** [comment]
The whole plugin will be rewritten using the API once that's done, so the plugin will be a lot smaller size and so you will be able to use the API 😄

**Comment by Sandertv** [comment]
Going to add the API into the wiki, so we can close this issue.
