### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by iPeedroPvP** [NL-4-DEVS/PocketRPG#39]
When killing receive items?

**Comment by Sandertv** [comment]
There's a switch in the config for setting keepinventory on in the rpg world :)

**Comment by iPeedroPvP** [comment]
example, when I kill someone get items? to go getting stronger, many rpg
servers so
Em 28 de set de 2016 14:45, "Blabla" <notifications@github.com> escreveu:

**Comment by Sandertv** [comment]
Nope, you can install a different plugin where you get items or points when killing someone thou Ghana.

**Comment by RedstoneAlmeida** [comment]
English : Disable KeepInventory in config.yml, or edit system to drop itens, blocking to no-drop right item 💃 
Português : Desabilite o KeepInventory na configuração ou edite o sistema de drops de itens, bloqueando para não dropar certo item

**Comment by iPeedroPvP** [comment]
Error on src\eventlistener\EventListener.php on line 395
Em 28 de set de 2016 14:50, "Blabla" <notifications@github.com> escreveu:

**Comment by Sandertv** [comment]
Fixed
