### ISSUE TITLE
1.0 Update Mage Wand Update

### ISSUE THREAD

**Issue by Sandertv** [NL-4-DEVS/PocketRPG#48]
In the 1.0 update the mage wand will change. Would anyone who knows how to spawn an invisible projectile make a pull request and help? I'm not an expert on this terrain. (Particle trails work already)

**Comment by Driesboy** [comment]
same for me 
i think you can ask jojoe

**Comment by Sandertv** [comment]
@jojoe77777 ?

**Comment by Driesboy** [comment]
Yes

Op 11-okt.-2016 20:49 schreef "Blabla" <notifications@github.com>:

**Comment by Sandertv** [comment]
I'm going to use a different way...
