### ISSUE TITLE
Quest system won't work

### ISSUE THREAD

**Issue by Adam1609** [NL-4-DEVS/PocketRPG#5]
Execute the command /quest choose but still it shows the message "You're already choose this quest", although I haven't choose any quests, and the config for quest won't work :(

**Comment by Sandertv** [comment]
Yeah it doesn't work yet, I'm working on a better way to create quests so I don't have to make a huge plugin for it...

**Comment by Adam1609** [comment]
Is this plugin inactive or something?

**Comment by Sandertv** [comment]
I'm working on a different way to make those quests... It's in a private repository so you can't see it but no it's not really inactive.

**Comment by Sandertv** [comment]
I am working on this now, with a bit of luck it should be working soon (it probably won't VERY soon but we can Always hope 😛 )

**Comment by Adam1609** [comment]
Suggestion: Adding Another Level System!

**Comment by Sandertv** [comment]
What do you have in mind for that?

**Comment by Sandertv** [comment]
Working quests in first release.
