### ISSUE TITLE
#OffTopic - Need help :)

### ISSUE THREAD

**Issue by WiliRodin** [NL-4-DEVS/PocketRPG#53]
I have a basic idea for a biome world generator. But im very noob developer.
Can u help me? my email is wrrs07@gmail.com
Thank you so much.

The error is
12.11 10:51:24 [Server] Server thread/INFO Se elimino 0 de lagg
12.11 10:50:44 [Disconnect] User DeadZenger has disconnected, reason: Kicked
12.11 10:50:44 [Server] Server thread/INFO DeadZenger left the game
12.11 10:50:40 [Multicraft] DeadZenger ran command Message of the Day
12.11 10:50:40 [Disconnect] User DeadZenger[/181.62.240.67:19132] [ClientID: 8939256840060461500] has disconnected, reason: unknown
12.11 10:50:40 [Connect] User DeadZenger, IP unknown
12.11 10:50:32 [Server] Server thread/INFO DeadZenger joined the game
12.11 10:50:31 [Multicraft] DeadZenger[/181.62.240.67:19132] [ClientID: 8939256840060461500] ran command Message of the Day
12.11 10:50:31 [Connect] User DeadZenger[/181.62.240.67:19132] [ClientID: 8939256840060461500], IP  
12.11 10:49:24 [Server] Server thread/INFO En un minuto de eliminara el lagg
12.11 10:49:20 [Server] Server thread/INFO [CONSOLE: Saved the world]
12.11 10:49:20 [Server] Server thread/INFO [CONSOLE: Saving...]
12.11 10:49:20 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
12.11 10:49:20 [Multicraft] Auto-saving world...
12.11 10:39:15 [Server] Server thread/INFO [CONSOLE: Saved the world]
12.11 10:39:15 [Server] Server thread/INFO [CONSOLE: Saving...]
12.11 10:39:15 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
12.11 10:39:15 [Multicraft] Auto-saving world...
12.11 10:34:44 [Server] Server thread/INFO Se elimino 0 de lagg
12.11 10:33:44 [Server] Server thread/INFO En un minuto de eliminara el lagg
12.11 10:29:09 [Server] Server thread/INFO [CONSOLE: Saved the world]
12.11 10:29:09 [Server] Server thread/INFO [CONSOLE: Saving...]
12.11 10:29:09 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
12.11 10:29:09 [Multicraft] Auto-saving world...
12.11 10:19:04 [Server] Server thread/INFO [CONSOLE: Saved the world]
12.11 10:19:04 [Server] Server thread/INFO [CONSOLE: Saving...]
12.11 10:19:04 [Server] Server thread/INFO [CONSOLE: Turned on world auto-saving]
12.11 10:19:04 [Multicraft] Auto-saving world...
12.11 10:18:04 [Server] Server thread/INFO En un minuto de eliminara el lagg
12.11 10:18:04 [Server] Server thread/INFO Se elimino 0 de lagg
12.11 10:18:04 [Server] Server thread/INFO [CONSOLE: Reload complete.]
12.11 10:18:04 [Server] Server thread/INFO [DreamWorldGenerator] 現在はダイヤモンドワールドを生成不可能な状態です。
12.11 10:18:04 [Server] Server thread/INFO [DreamWorldGenerator] =================================
12.11 10:18:04 [Server] Server thread/INFO [DreamWorldGenerator] 二次配布、改造配布は禁止です。 製作者gigantessbeta
12.11 10:18:04 [Server] Server thread/INFO [DreamWorldGenerator] このプラグインにはWorld生成系、移動系プラグインが必須です。
12.11 10:18:04 [Server] Server thread/INFO [DreamWorldGenerator] DreamWorldGenerator をご利用いただき、ありがとうございます。
12.11 10:18:04 [Server] Server thread/INFO Enabling DreamWorldGenerator v0.1.2
12.11 10:18:04 [Server] Server thread/INFO Enabling iProtector v3.1b
12.11 10:18:04 [Server] Server thread/INFO [ChatWorldPlus] ChatWorldPlusの読み込みが完了しました
12.11 10:18:04 [Server] Server thread/INFO Enabling ChatWorldPlus v0.1.1
12.11 10:18:04 [Server] Server thread/INFO Disabling Forest1 v1
12.11 10:18:04 [Server] Server thread/CRITICAL Error: "Call to undefined method Generator::addGenerator()" (EXCEPTION) in "/Forest.phar/src/generator/Main" at line 12
12.11 10:18:04 [Server] Server thread/INFO Enabling Forest1 v1

**Comment by Sandertv** [comment]
I would like to help but too bad I have no experience with biome generation at all.

**Comment by WiliRodin** [comment]
I send you the source code.
Reply me on Email please ^^
