### ISSUE TITLE
Request-API_3.0.0_Support

### ISSUE THREAD

**Issue by Starflux** [NL-4-DEVS/PocketRPG#55]
PocketMine-MP version 1.6.2dev "Unleashed" (API 3.0.0-ALPHA3)
PHP 7.0.15

**PocketRPG v0.3.0**

i understand that the plugin i downloaded from poggit does not support API 3.0.0 are you looking to update this?

i amended the api line for 3.0.0-ALPHA3 and recieved the following:

**Console:**
[08:28:09] [Server thread/INFO]: Enabling PocketRPG v0.3.0
[08:28:09] [Server thread/INFO]: [PocketRPG] Enabling PocketRPG
[08:28:09] [Server thread/CRITICAL]: ReflectionException: "Class pocketmine\event\player\PlayerExperienceChangeEvent does not exist" (EXCEPTION) in "/src/pocketmine/plugin/PluginManager" at line 723
[08:28:09] [Server thread/INFO]: Disabling PocketRPG v0.3.0
[08:28:09] [Server thread/INFO]: [PocketRPG] Disabling PocketRPG

i am really interested in the quests side of the plugin.

thankyou for the great work you have done.

Kind Regards
Star

**Comment by Sandertv** [comment]
I kinda abandoned this plugin because it's so horribly messy and only works for forks of PocketMine. If you want I can separate the quests part of the plugin for you.

**Comment by Starflux** [comment]
i would really like that but only if you have the time to do it.

i used to use a plugin on the PC edition https://www.spigotmc.org/resources/quests.3711/ 

is it possible with pocketmine to use a book to log the current quests the player has accepted?

**Comment by Sandertv** [comment]
Sorry for the extreme delay. I've made a proper quest plugin here: https://github.com/BlockHorizons/BlockQuests
If you got suggestions, feel free to suggest them there.

**Comment by HimbeersaftLP** [comment]
![R.I.P. PocketRPG](http://www.tombstonebuilder.com/generate.php?top1=R.I.P.&top2=PocketRPG&top3=2016-2017&top4=&sp=)

**Comment by Sandertv** [comment]
Lmao ikr @HimbeersaftLP
