### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Sandertv** [NL-4-DEVS/PocketRPG#8]
Please post your suggestions for this plugin down below!

**Comment by CaptainDuck** [comment]
Parties! :P

**Comment by Sandertv** [comment]
Lol I completely forgot about that! Good idea ;)

**Comment by RedstoneAlmeida** [comment]
Suggestions:

- XP using Money Sistem
- Buy New Itens Enchanted or Armor
- Create More One personages
- Party System

**Comment by Sandertv** [comment]
I left the rewards kind of free so you can make things yourself, for example use emeralds to give out and make a sell sign for money. The party system is being worked on and nearly finished, i might make a new character later and what exactly do you mean with XP using Money System?

**Comment by CaptainDuck** [comment]
Add Archer!
I think what Redstone means is that, XP will be replaced as the money.. It will be used for the Buy and sell things :P

**Comment by Sandertv** [comment]
Oh if that's the case... idk really lol, right now the plugin doesn't do a whole lot with economy :P.Anyways I wasn't quite sure about the archer class (I had it included earlier) since the bow still isn't as flawless as you'd like on most PE server softwares which could get archer a really weak class...

**Comment by CaptainDuck** [comment]
:( but I love archer xd

**Comment by Praxthisnovcht** [comment]
hi, I think we should ask to confirm your class of choice.
Example: when you type / rpg start mage he asked to be on it again to

**Comment by Sandertv** [comment]
Ohh I get what you mean! I'll see what I can do! :)

**Comment by Sandertv** [comment]
I'm going to add this in the 0.4 update @Praxthisnovcht

**Comment by Sandertv** [comment]
@Praxthisnovcht could you test the Beta branch? It has the features added and should hopefully work :)

**Comment by Praxthisnovcht** [comment]
I'm going to try

**Comment by Sandertv** [comment]
Any results?

**Comment by Sandertv** [comment]
Okay it should be working now, try it now @Praxthisnovcht

**Comment by iiInfinityHD** [comment]
Money reward for quest

**Comment by Sandertv** [comment]
I might add commands to execute when finishing a quest.
