### ISSUE TITLE
Beta Error

### ISSUE THREAD

**Issue by RedstoneAlmeida** [NL-4-DEVS/PocketRPG#9]
`[18:10:06] [Server thread/CRITICAL]: ParseError: "syntax error, unexpected ';'" (EXCEPTION) in "/plugins/PocketRPG-beta/src/PocketRPG/eventlistener/EventListener" at line 72
`

**Comment by Sandertv** [comment]
Whoops thanks! I'll be fixing this soon, try to use the stable release for now :)

**Comment by Sandertv** [comment]
Would you mind testing the beta right now and tell me if it works?

**Comment by RedstoneAlmeida** [comment]
i have tested bug is fixed thanks 👍

**Comment by Sandertv** [comment]
Good!
